"""Initial migration.

Revision ID: ac1d8d272553
Revises: 
Create Date: 2024-02-26 09:56:06.056014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1d8d272553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_token_block_list_jti'), ['jti'], unique=False)

    op.create_table('token_block_list_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.String(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_id'), ['id'], unique=False)

    op.create_table('users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_end_transaction_id'))

    op.drop_table('users_version', schema='public')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_id'))

    op.drop_table('users', schema='public')
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_jti'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'))

    op.drop_table('token_block_list_version', schema='public')
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_jti'))

    op.drop_table('token_block_list', schema='public')
    # ### end Alembic commands ###
